site_name: Disney Plus

repo_name: '2021.1-DisneyPlus'
repo_url: 'https://github.com/Requisitos-de-Software/2021.1-DisneyPlus'

theme:
  name: material
  language: 'pt'
  logo: 'assets/favicon.ico'
  favicon: 'assets/favicon.ico'
  palette:
    primary: '#fff'
    accent: 'light blue'
  font:
    text: 'Montserrat'
    code: 'sans-serif'

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Planejamento:
      - Metodologia: planejamento/metodologia.md
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
  - Pré-rastreabilidade:
      - RichPictures: pre_rastreabilidade/rich_pictures.md
  - Elicitação:
      - Personas: elicitacao/personas.md
      - Técnicas:
          - Brainstorming: elicitacao/tecnicas/brainstorm.md
          - Observação: elicitacao/tecnicas/observacao.md
          - Introspecção: elicitacao/tecnicas/introspeccao.md
          - Questionário: elicitacao/tecnicas/questionario.md
      - Priorização:
          - MoSCoW: elicitacao/priorizacao/moscow.md
      - Resultado: elicitacao/resultado.md
  - Modelagem:
      - Especificação Suplementar: modelagem/especificacao_suplementar.md
      - Cenários: modelagem/cenarios.md
      - Léxicos: modelagem/lexicos.md
      - Casos de Uso: modelagem/casos_de_uso.md
      - Backlog:
          - Backlog do produto: modelagem/backlog/backlog.md
          - EP01 - Conta: modelagem/backlog/ep01_conta.md
          - EP02 - Perfil: modelagem/backlog/ep02_perfil.md
          - EP03 - Conteúdo: modelagem/backlog/ep03_conteudo.md
  - Análise:
      - Verificação:
          - Verificação: analise/verificacao/verificacao.md
          - NFR Framework: analise/verificacao/nfr_framework.md
          - Rich Picture: analise/verificacao/rich_picture.md
          - Backlog: analise/verificacao/backlog.md
          - Casos de Uso: analise/verificacao/casos_de_uso.md
          - Cenários: analise/verificacao/cenarios.md
          - Léxicos: analise/verificacao/lexicos.md
      - Validação:
          - Prototipação: anailse/validacao/prototipacao_md 
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentação 4: apresentacoes/apresentacao4.md

dev_addr: '0.0.0.0:8000'
